### ISSUE TITLE
Bootsnap permission issue on macOS

### ISSUE THREAD

**Issue by yannbolliger** [hitobito/development#21]
While following along the instructions of the README on macOS 10.15.7, I hit this exact issue:
https://github.com/Shopify/bootsnap/issues/353

More precisely, any of the containers `rails`, `webpack` or `worker` could fail with this log output:
<details>
<summary>
log output of failing Rails container
</summary>

```
...
rails_1        | Bundle complete! 113 Gemfile dependencies, 254 gems now installed.
rails_1        | Bundled gems are installed into `/opt/bundle`
rails_1        | ⚙️  Testing DB connection
rails_1        | ✅ DB server is ready
rails_1        | ⚙️  Performing migrations
rails_1        | rails aborted!
rails_1        | Errno::EPERM: Operation not permitted - bs_fetch:atomic_write_cache_file:chmod
rails_1        | /opt/bundle/gems/bootsnap-1.4.5/lib/bootsnap/compile_cache/iseq.rb:37:in `fetch'
rails_1        | /opt/bundle/gems/bootsnap-1.4.5/lib/bootsnap/compile_cache/iseq.rb:37:in `load_iseq'
rails_1        | /opt/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
rails_1        | /opt/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
rails_1        | /opt/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
rails_1        | /opt/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
rails_1        | /opt/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
rails_1        | /opt/bundle/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `block in require'
rails_1        | /opt/bundle/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
rails_1        | /opt/bundle/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `require'
rails_1        | /opt/bundle/gems/railties-6.0.3.4/lib/rails/engine.rb:4:in `<main>'
rails_1        | /opt/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
rails_1        | /opt/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
rails_1        | /opt/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
rails_1        | /opt/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
rails_1        | /opt/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
rails_1        | /opt/bundle/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `block in require'
rails_1        | /opt/bundle/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
rails_1        | /opt/bundle/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `require'
rails_1        | /opt/bundle/gems/railties-6.0.3.4/lib/rails/application.rb:11:in `<main>'
rails_1        | /opt/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
rails_1        | /opt/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
rails_1        | /opt/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
rails_1        | /opt/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
rails_1        | /opt/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
rails_1        | /opt/bundle/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `block in require'
rails_1        | /opt/bundle/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
rails_1        | /opt/bundle/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `require'
rails_1        | /opt/bundle/gems/railties-6.0.3.4/lib/rails.rb:14:in `<main>'
rails_1        | /opt/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
rails_1        | /opt/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
rails_1        | /opt/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
rails_1        | /opt/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
rails_1        | /opt/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
rails_1        | /opt/bundle/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `block in require'
rails_1        | /opt/bundle/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
rails_1        | /opt/bundle/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `require'
rails_1        | /opt/bundle/gems/railties-6.0.3.4/lib/rails/all.rb:5:in `<main>'
rails_1        | /opt/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
rails_1        | /opt/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
rails_1        | /opt/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
rails_1        | /opt/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
rails_1        | /opt/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
rails_1        | /opt/bundle/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `block in require'
rails_1        | /opt/bundle/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
rails_1        | /opt/bundle/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `require'
rails_1        | /usr/src/app/hitobito/config/application.rb:8:in `<main>'
rails_1        | /opt/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
rails_1        | /opt/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
rails_1        | /opt/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
rails_1        | /opt/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
rails_1        | /opt/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
rails_1        | /opt/bundle/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `block in require'
rails_1        | /opt/bundle/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
rails_1        | /opt/bundle/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `require'
rails_1        | /usr/src/app/hitobito/rakefile:12:in `<main>'
rails_1        | /opt/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
rails_1        | /opt/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
rails_1        | /opt/bundle/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:318:in `block in load'
rails_1        | /opt/bundle/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
rails_1        | /opt/bundle/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:318:in `load'
rails_1        | /opt/bundle/gems/railties-6.0.3.4/lib/rails/commands/rake/rake_command.rb:22:in `block in perform'
rails_1        | /opt/bundle/gems/railties-6.0.3.4/lib/rails/commands/rake/rake_command.rb:20:in `perform'
rails_1        | /opt/bundle/gems/railties-6.0.3.4/lib/rails/command.rb:48:in `invoke'
rails_1        | /opt/bundle/gems/railties-6.0.3.4/lib/rails/commands.rb:18:in `<main>'
rails_1        | /opt/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
rails_1        | /opt/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
rails_1        | /opt/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
rails_1        | /opt/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
rails_1        | /opt/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
rails_1        | /opt/bundle/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `block in require'
rails_1        | /opt/bundle/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
rails_1        | /opt/bundle/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `require'
rails_1        | bin/rails:4:in `<main>'
rails_1        | (See full trace by running task with --trace)
pbs_rails_1 exited with code 1

```
</details>

**Comment by carlobeltrame** [comment]
Thanks for the report! It looks to me like we simply need to update bootsnap to a version >= 1.7.4 in hitobito core, would you agree?

Maybe you can test this theory by running: `docker-compose run --entrypoint "bundle update bootsnap" rails` on your machine, then starting the containers and see if it helps in your case? If so, we can integrate this change into hitobito core.

**Comment by yannbolliger** [comment]
I can confirm that updating bootsnap via one-off command resolves the problem locally.
Thank you for the help. 🚀
